appetizer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from about_us.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home_page'),

    path('meals/', include(('meals.urls', 'meals'), namespace='meals')),
    path('reservation/', include(('reservation.urls', 'reservation'), namespace='reservation')),
    path('contact_us/', include(('contact.urls', 'contact'), namespace='contact')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('about_us/', include(('about_us.urls', 'about_us'), namespace='about_us')),
    path('catering/', include(('catering.urls', 'catering'), namespace='catering')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('user/', include(('user.urls', 'user'), namespace='user')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import posts_list, posts_categories, post_leave_comment, tags_list
from .views import PostDetail, TagDetail


urlpatterns = [
    path('', posts_list, name='posts_list_url'),
    path('categories', posts_categories, name='posts_categories_url'),
    path('post/<str:slug>', PostDetail.as_view(), name='post_details_url'),
    path('comment/<str:slug>', post_leave_comment, name='post_leave_comment_url'),
    path('tag_s', tags_list, name='tags_list_url'),
    path('tag/<str:slug>/', TagDetail.as_view(), name='tag_details_url'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from meals.models import get_slug


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 1 автор к множеству постов
    category = models.ForeignKey('Category', null=True, on_delete=models.SET_NULL)  # 1 категория к множеству постов
    image = models.ImageField(upload_to='posts/', null=True)
    slug = models.SlugField(max_length=150, blank=True, null=True, unique=True)
    tags = models.ManyToManyField('Tag', related_name='posts')

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"
        ordering = ['-created_date']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_slug(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_details_url', kwargs={'slug': self.slug})

    def get_comment_url(self):
        return reverse('blog:post_leave_comment_url', kwargs={'slug': self.slug})

    def __str__(self):
        return f"{self.title}"


class Category(models.Model):
    category_name = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return f"{self.category_name}"


class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        ordering = ['title']

    def get_absolute_url(self):
        return reverse('blog:tag_details_url', kwargs={'slug': self.slug})

    def __str__(self):
        return f"{self.title}"


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # 1 юзер - много комментов
    post = models.ForeignKey(Post, on_delete=models.CASCADE)  # 1 пост - много комментов
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.content}"

blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control',
                                             'placeholder': 'Type your comment here...', 'required': 'required'})
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import View

from .forms import CommentForm
from .models import Post, Category, Tag
from .utils import ObjectDetailMixin, PostDetailMixin
from appetizer.settings import POSTS_PER_PAGES


def posts_search(request):
    search_query = request.GET.get('search', '')
    if search_query:
        posts = Post.objects.filter(
            Q(title__icontains=search_query) |
            Q(content__icontains=search_query) |
            Q(tags__title__icontains=search_query)
        ).distinct()
    else:
        posts = Post.objects.all()
    return posts


def posts_pagination(request):
    paginator = Paginator(posts_search(request), POSTS_PER_PAGES)

    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    is_paginated = page.has_other_pages()

    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    return {
        'page_obj': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url
    }


def posts_list(request):
    return render(request, 'blog.html',
                  context=posts_pagination(request))


def posts_categories(request):
    posts = Post.objects.all()
    categories = Category.objects.all()

    return render(request, 'posts_categories.html', {
        'posts': posts,
        'categories': categories
    })


@login_required()
def post_leave_comment(request, slug):
    post_details = Post.objects.get(slug=slug)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post_details
            new_comment.save()
            return redirect('blog:post_details_url', slug=slug)
    else:
        comment_form = CommentForm()

    return render(request, 'leave_comment.html', {
        'post_details': post_details,
        'form': comment_form
    })


def tags_list(request):
    tags = Tag.objects.all()
    return render(request, 'tags.html', {
        'tags': tags
    })


class PostDetail(PostDetailMixin, View):
    model = Post
    template = 'post_details.html'


class TagDetail(ObjectDetailMixin, View):
    model = Tag
    template = 'tag_details.html'

blog/templates/includes/post_body_card.html
<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="panel panel-default">
        <div class="panel-body">
            <img src="{{ post.image.url }}"
                 alt="" class="img-thumbnail img-responsive">
            <p class="text-muted">
                <span class="glyphicon glyphicon-user" aria-hidden="true">By</span>
                {{ post.author.first_name }} {{ post.author.last_name }}
                <span class="glyphicon glyphicon-calendar" aria-hidden="true">|</span>
                {{ post.created_date }}
                <span class="pull-right">
                    <a href="{{ post.get_comment_url }}">
                        <i class="fa fa-comment site-main-color"></i>
                    </a>
                </span>
            </p>
            <h3>{{ post.title|truncatewords:6 }}</h3>
            <p>{{ post.content|truncatewords:25 }}</p>
            <a href="{{ post.get_absolute_url }}" class="btn btn-default">View more...</a>
        </div>
    </div>
</div>

blog/templates/includes/post_search.html
<form action="{% url 'blog:posts_list_url' %}" method="GET"
      class="form-inline justify-content-center">
    <div class="form-group">
        <label>
            <input type="text" class="form-control" name="search"
                   value="{{ request.get.search }}"
                   placeholder="Search...">
        </label>
        <button type="submit" class="btn btn-success post-search-btn">
            <i class="fa fa-search"></i>
        </button>
    </div>
</form>

blog/templates/includes/posts_pagination.html
<nav>
    <div class="paginator text-center">

        <span class="page-item" style="{% if not prev_url %} opacity: 0.3; {% endif %}">
            <a href="{{ prev_url }}" class="btn-default"><span aria-hidden="true">←</span> Newer Posts</a>
        </span>

        {% for n in page_obj.paginator.page_range %}

            {% if page_obj.number == n %}
                <span class="page-item">
                    <a href="?page={{ n }}" class="btn-default btn-pagination">{{ n }}</a>
                </span>

            {% elif n > page_obj.number|add:-2 and n < page_obj.number|add:2 %}
                <span class="page-item">
                    <a href="?page={{ n }}" class="btn-default">{{ n }}</a>
                </span>
            {% endif %}

        {% endfor %}

        <span class="page-item" style="{% if not next_url %} opacity: 0.3; {% endif %}">
            <a href="{{ next_url }}" class="btn-default">
                Older Posts<span aria-hidden="true">→</span></a>
        </span>

    </div>
</nav>