appetizer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from about_us.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home_page'),

    path('meals/', include(('meals.urls', 'meals'), namespace='meals')),
    path('reservation/', include(('reservation.urls', 'reservation'), namespace='reservation')),
    path('contact_us/', include(('contact.urls', 'contact'), namespace='contact')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('about_us/', include(('about_us.urls', 'about_us'), namespace='about_us')),
    path('catering/', include(('catering.urls', 'catering'), namespace='catering')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('user/', include(('user.urls', 'user'), namespace='user')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import posts_list, posts_categories, post_leave_comment, tags_list
from .views import PostDetail, TagDetail


urlpatterns = [
    path('', posts_list, name='posts_list_url'),
    path('categories', posts_categories, name='posts_categories_url'),
    path('post/<str:slug>', PostDetail.as_view(), name='post_details_url'),
    path('comment/<str:slug>', post_leave_comment, name='post_leave_comment_url'),
    path('tag_s', tags_list, name='tags_list_url'),
    path('tag/<str:slug>/', TagDetail.as_view(), name='tag_details_url'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from meals.models import get_slug


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 1 автор к множеству постов
    category = models.ForeignKey('Category', null=True, on_delete=models.SET_NULL)  # 1 категория к множеству постов
    image = models.ImageField(upload_to='posts/', null=True)
    slug = models.SlugField(max_length=150, blank=True, null=True, unique=True)
    tags = models.ManyToManyField('Tag', related_name='posts')

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"
        ordering = ['-created_date']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_slug(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_details_url', kwargs={'slug': self.slug})

    def get_comment_url(self):
        return reverse('blog:post_leave_comment_url', kwargs={'slug': self.slug})

    def __str__(self):
        return f"{self.title}"


class Category(models.Model):
    category_name = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return f"{self.category_name}"


class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        ordering = ['title']

    def get_absolute_url(self):
        return reverse('blog:tag_details_url', kwargs={'slug': self.slug})

    def __str__(self):
        return f"{self.title}"


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # 1 юзер - много комментов
    post = models.ForeignKey(Post, on_delete=models.CASCADE)  # 1 пост - много комментов
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.content}"

blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control',
                                             'placeholder': 'Type your comment here...', 'required': 'required'})
        }

blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import View

from .forms import CommentForm
from .models import Post, Category, Tag
from .utils import ObjectDetailMixin, PostDetailMixin
from appetizer.settings import POSTS_PER_PAGES


def posts_search(request):
    search_query = request.GET.get('search', '')
    if search_query:
        posts = Post.objects.filter(
            Q(title__icontains=search_query) |
            Q(content__icontains=search_query) |
            Q(tags__title__icontains=search_query)
        ).distinct()
    else:
        posts = Post.objects.all()
    return posts


def posts_pagination(request):
    paginator = Paginator(posts_search(request), POSTS_PER_PAGES)

    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    is_paginated = page.has_other_pages()

    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''

    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''

    return {
        'page_obj': page,
        'is_paginated': is_paginated,
        'next_url': next_url,
        'prev_url': prev_url
    }


def posts_list(request):
    return render(request, 'blog.html',
                  context=posts_pagination(request))


def posts_categories(request):
    posts = Post.objects.all()
    categories = Category.objects.all()

    return render(request, 'posts_categories.html', {
        'posts': posts,
        'categories': categories
    })


@login_required()
def post_leave_comment(request, slug):
    post_details = Post.objects.get(slug=slug)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post_details
            new_comment.save()
            return redirect('blog:post_details_url', slug=slug)
    else:
        comment_form = CommentForm()

    return render(request, 'leave_comment.html', {
        'post_details': post_details,
        'form': comment_form
    })


def tags_list(request):
    tags = Tag.objects.all()
    return render(request, 'tags.html', {
        'tags': tags
    })


class PostDetail(PostDetailMixin, View):
    model = Post
    template = 'post_details.html'


class TagDetail(ObjectDetailMixin, View):
    model = Tag
    template = 'tag_details.html'

blog/templates/blog.html
{% extends 'base.html' %}

{% block title %}
    News Appetizer
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}

    <div class="container">

        <div class="row">

            <div class="col-xl-12 text-center">
                <div class="section-title text-center mb-60">

                    <p class="blog-m">Famous for good food</p>
                    <h4>Latest news</h4>
                    <div>
                        <h4><a href="{% url 'blog:tags_list_url' %}">#Tags</a></h4>
                    </div>
                    <div>
                        <h4><a href="{% url 'blog:posts_categories_url' %}">Categories</a></h4>
                    </div>

                    <div class="row">
                        <div class="col-sm-10 col-md-10 offset-sm-1 text-center">
                            <div class="info-form">
                                {% include 'includes/post_search.html' %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-6 col-md-12 col-lg-12">
                <div class="row">
                    {% for post in page_obj.object_list %}
                        {% include 'includes/post_body_card.html' %}
                    {% endfor %}
                </div>
                <hr>
                <div>
                    {% if is_paginated %}
                        {% include 'includes/posts_pagination.html' %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/leave_comment.html
{% extends 'base.html' %}
<meta name="csrf_token" content="{{ csrf_token }}">
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

{% block title %}
    Leave comment
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="container">
        <h2 class="text-center p-details">
            Leave Comment
        </h2>
        <div class="card">
            <div class="card-body">
                <form action="" method="post" class="p-5 bg-light">
                    {% csrf_token %}
                    {% for field in form %}

                        {{ field }}

                    {% endfor %}
                    <button type="submit" class="btn btn-default">Leave comment</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/post_details.html
{% extends 'base.html' %}
<meta name="csrf_token" content="{{ csrf_token }}">
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

{% block title %}
    {{ post.title }} - {{ block.super }}
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
    <section class="pd-section">
        <header class="header text-center">
            <h1 class="header-h1">{{ post.title }}</h1>
        </header>
        <div class="background-bar"></div>
        <section class="container-fluid main-body">
            <section class="row">
                <div class="hidden-xs col-sm-1 col-md-2"></div>
                <div class="col-xs-12 col-sm-10 col-md-8">
                    <div class="content-holder">
                        <div class="content-description">

                            <div class="author-name">
                                <h3>Author: {{ post.author.first_name }} {{ post.author.last_name }}</h3>
                            </div>
                            <div class="row blog-info">
                                <div class="col-xs-12 col-sm-6">
                                    <span class="lead text-muted"><i class="fa fa-clock-o"></i>
                                        Published: {{ post.created_date }}
                                    </span>
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    <span class="lead text-muted"><i class="fa fa-tags"></i>
                                        {% for tag in post.tags.all %}
                                            <span class="badge tag-badge-post-body">
                                                <a href="{{ tag.get_absolute_url }}" class="link-badge pd-link">
                                                    {{ tag.title }}
                                                </a>
                                            </span>
                                        {% endfor %}
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="content-body">
                            <p>
                            <blockquote>
                                {{ post.content }}
                            </blockquote>
                            </p>

                            <div class="container">
                                <h2 class="text-center p-details">Comments</h2>
                                <div class="card">
                                    <div class="card-body">
                                        <div class="row">
                                            {% for comment in comments %}
                                                <div class="col-md-2">
                                                    <img src="https://image.ibb.co/jw55Ex/def_face.jpg"
                                                         class="img img-rounded img-fluid"/>
                                                    <small class="text-secondary text-center">{{ comment.user.last_login }}</small>
                                                </div>
                                                <div class="col-md-10">
                                                    <p>
                                                        <strong>{{ comment.user.first_name }} {{ comment.user.last_name }}</strong>
                                                    </p>
                                                    <div class="clearfix"></div>
                                                    <p>{{ comment.content }}</p>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <a href="{{ post.get_comment_url }}" class="btn btn-default">Leave Comment</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </section>
    </section>
{% endblock %}

blog/templates/posts_categories.html
{% extends 'base.html' %}

{% block title %}
    News Categories
{% endblock %}

{% block header %}
    <header class="header text-center">
        <h1 class="header-h1">News Categories</h1>
    </header>
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">

            <!-- Nav pills -->

            <ul class="nav nav-tabs menu_tab pc-ul" role="tablist">
                {% for category in categories %}
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="pill" href="#{{ category }}">{{ category }}</a>
                    </li>
                {% endfor %}
            </ul>

            <div class="tab-content slideanim">
                {% for category in categories %}
                    <div id="{{ category }}" class="tab-pane fade show">
                        <div class="col-sm-6 col-md-12 col-lg-12">
                            <div class="row">
                                {% for post in posts %}
                                    {% if post.category == category %}
                                        {% include 'includes/post_body_card.html' %}
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <hr>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/tag_details.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.title }} - {{ block.super }}
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
    <section class="td-section">
        <header class="header text-center">
            <h1 class="header-h1">#{{ tag.title|lower }}</h1>
        </header>
        <div class="container">
            <div class="col-sm-6 col-md-12 col-lg-12">
                <div class="row">
                    {% for post in tag.posts.all %}
                        {% include 'includes/post_body_card.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

blog/templates/tags.html
{% extends 'base.html' %}

{% block title %}
    News Tags
{% endblock %}

{% block header %}
    <header class="header text-center">
            <h1 class="header-h1">#Tags</h1>
        </header>
{% endblock %}

{% block content %}
<div class="item">
    <div class="item-content-block tags tags-center">
        {% for tag in tags %}
    	    <span class="badge tag-badge-details">
                <a href="{{ tag.get_absolute_url }}" class="btn btn-default">
                    {{ tag.title }}
                </a>
            </span>
        {% endfor %}
    </div>
</div>
{% endblock %}