appetizer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from about_us.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home_page'),

    path('meals/', include(('meals.urls', 'meals'), namespace='meals')),
    path('reservation/', include(('reservation.urls', 'reservation'), namespace='reservation')),
    path('contact_us/', include(('contact.urls', 'contact'), namespace='contact')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('about_us/', include(('about_us.urls', 'about_us'), namespace='about_us')),
    path('catering/', include(('catering.urls', 'catering'), namespace='catering')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('user/', include(('user.urls', 'user'), namespace='user')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import posts_list, posts_categories, post_leave_comment, tags_list
from .views import PostDetail, TagDetail


urlpatterns = [
    path('', posts_list, name='posts_list_url'),
    path('categories', posts_categories, name='posts_categories_url'),
    path('post/<str:slug>', PostDetail.as_view(), name='post_details_url'),
    path('comment/<str:slug>', post_leave_comment, name='post_leave_comment_url'),
    path('tag_s', tags_list, name='tags_list_url'),
    path('tag/<str:slug>/', TagDetail.as_view(), name='tag_details_url'),
]

catering/urls.py
from django.urls import path
from .views import catering_products_list, catering_product_details


urlpatterns = [
    path('', catering_products_list, name='catering_products_list_url'),
    path('<str:slug>', catering_product_details, name='catering_product_details_url'),
]

order/urls.py
from django.urls import path
from .views import order_create, order_history, order_details


urlpatterns = [
    path('create_order/', order_create, name='order_create_url'),
    path('order_history/', order_history, name='order_history_url'),
    path('order_details/<int:order_id>', order_details, name='order_details_url'),

]

order/models.py
from math import fsum
from django.db import models

from catering.models import CateringProduct


class Order(models.Model):
    email = models.EmailField(max_length=100, blank=True, verbose_name='Email Address')
    phone = models.CharField(max_length=100, blank=True)
    billing_first_name = models.CharField(max_length=250, blank=True)
    billing_last_name = models.CharField(max_length=250, blank=True)
    billing_address = models.CharField(max_length=250, blank=True)
    billing_postal_code = models.CharField(max_length=10, blank=True)
    billing_city = models.CharField(max_length=250, blank=True)
    billing_country = models.CharField(max_length=100, blank=True, default='Ukraine')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']

    def get_totals(self):
        return fsum(order_item.sub_total() for order_item in self.items.all())

    def __str__(self):
        return f'{self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(CateringProduct, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='USD Price')
    quantity = models.PositiveIntegerField()

    def sub_total(self):
        return self.quantity * self.price

    def __str__(self):
        return f'{self.product}'

order/forms.py
from django import forms

from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['billing_first_name', 'billing_last_name',
                  'phone', 'email', 'billing_address', 'billing_postal_code',
                  'billing_city']

        widgets = {
            'billing_first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'billing_last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '+38093 777 7777', 'required': 'required'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'appetizer@email.com'}),
            'billing_address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
            'billing_postal_code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '01034'}),
            'billing_city': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City'}),
        }

order/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Order, OrderItem
from .forms import OrderCreateForm

from cart.models import Cart, CartItem
from catering.models import CateringProduct
from cart.views import _cart_id


def order_create(request, total=0):

    order_form = OrderCreateForm()
    cart = Cart.objects.get(cart_id=_cart_id(request))
    cart_items = CartItem.objects.filter(cart=cart, active=True)

    for cart_item in cart_items:
        total += cart_item.product.price * cart_item.quantity

    if request.method == 'POST':
        order_form = OrderCreateForm(request.POST)
        if order_form.is_valid():
            order_form = order_form.save()

            for cart_item in cart_items:

                order_item = OrderItem.objects.create(
                    order=order_form,
                    product=cart_item.product,
                    price=cart_item.product.price,
                    quantity=cart_item.quantity
                )
                order_item.save()

                # Reduce stock
                product = CateringProduct.objects.get(slug=cart_item.product.slug)
                product.stock = int(cart_item.product.stock - cart_item.quantity)
                product.save()

                cart_item.delete()

        return render(request, 'creation_order_success.html')

    return render(request, 'create_order.html', {
        'form': order_form,
        'cart_items': cart_items,
        'total': total
    })


@login_required()
def order_history(request):
    if request.user.is_authenticated:
        email = str(request.user.email)
        orders = Order.objects.filter(email=email)
        return render(request, 'orders_list.html', {
            'orders': orders
        })


@login_required()
def order_details(request, order_id):
    if request.user.is_authenticated:
        email = str(request.user.email)
        order = Order.objects.get(id=order_id, email=email)
        order_items = OrderItem.objects.filter(order=order)
        return render(request, 'order_details.html', {
            'order': order,
            'order_items': order_items
        })

order/templates/create_order.html
{% extends 'base.html' %}

{% block title %}
    Your Ordering Cart| Checkout
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row order-row">
            <div class="col-md-6">
                <hr>
                <h1 class="page-header">Checkout</h1>
                <hr>
                <form action="" method="post">
                    <div class="row">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="col-md-6">
                                <div class="form-group">

                                    {{ field.label|title }}
                                    {{ field }}

                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-md-12 mt-3 contact-buttons text-center">
                            <input type="submit" class="btn btn-primary order-btn" value="Submit order">
                            <input type="reset" class="btn btn-primary order-btn" value="Reset"/>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-6">
                <hr>
                <h1 class="page-header">Your Order</h1>
                <hr>
                <ul class="list-group">
                    {% for cart_item in cart_items %}
                        <li class="list-group-item">
                            <span><b>{{ cart_item.product.name }}</b></span>
                            <span>{{ cart_item.quantity }} x {{ cart_item.product.price }}</span>
                            <span><b>Cost:</b> {{ cart_item.sub_total }}</span>
                        </li>
                    {% endfor %}

                    <li class="list-group-item active" style="background-color: #182c39;">
                        <b>Total Cost:</b><strong>${{ total }}</strong>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

order/templates/creation_order_success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Order is completed
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="text-center">
            <hr>
            <h1>Thank You For Choosing Us</h1>
            <hr>
            <p>Your order has been successfully completed.</p>
            <p>Our admin will connect with you...</p>
            <p>Please click
                <a href="{% url 'catering:catering_products_list_url' %}">
                    to continue ordering</a>
            </p>
        </div>
    </div>
{% endblock %}

order/templates/order_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Orders History
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="container">
        <hr>
        <h1>Order Details</h1>
        <hr>
        <table class="table table-bordered">
            <tr>
                <td class="text-left" colspan="2">
                    <p><b>Order: </b>#{{ order.id }}</p>
                    <p><b>Date: </b>{{ order.created|date:"d M Y" }}</p>
                    <p><b>Order Total: </b>${{ order.get_totals }}</p>
                    <p><b>Order Status: </b><i class="fa fa-check"></i>&nbsp;Complete</p>
                </td>
                <td class="text-left" colspan="2">
                    <p><b>Billing Address: </b></p>
                    <p>{{ order.billing_first_name }}</p>
                    <p>{{ order.billing_last_name }}</p>
                    <p>{{ order.billing_postal_code }}</p>
                    <p>{{ order.billing_city }}</p>
                    <p>{{ order.billing_address }}</p>
                </td>
            </tr>
            <tr>
                <td><b>Product Description</b></td>
                <td><b>Quantity</b></td>
                <td><b>Unit Price</b></td>
                <td><b>Sub-Total</b></td>
            </tr>
            {% for item in order_items %}
                <tr>
                    <td>{{ item.product }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.price }}</td>
                    <td>{{ item.sub_total }}</td>
                </tr>
            {% endfor %}
            <tr>
                <td class="text-right" colspan="3"><b>Total</b></td>
                <td>{{ order.get_totals }}</td>
            </tr>
            <tr>
                <td class="text-right" colspan="3"><b>Total Paid</b></td>
                <td>{{ order.get_totals }}</td>
            </tr>
        </table>
        <button class="btn btn-default" onclick="window.print();">
            Print Order <i class="fa fa-print" aria-hidden="true"></i>
        </button>
    </div>
{% endblock %}

order/templates/orders_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Orders History
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="text-center">
            <hr>
            <h1>Orders History</h1>
            <hr>
            {% if orders %}
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Order Date</th>
                        <th>Total Amount</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <td>{{ order.id }}</td>
                            <td>{{ order.created|date:"d M Y" }}</td>
                            <td>{{ order.get_totals }}</td>
                            <td><i class="fa fa-check"></i>&nbsp;Complete</td>
                            <td><a href="{% url 'order:order_details_url' order.id %}">View order</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div>
                    <p>You have not placed any orders yet.</p>
                    <p>
                        <a href="{% url 'catering:catering_products_list_url' %}" class="btn btn-default order-lis-btn">
                            Continue Ordering
                        </a>
                    </p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}