appetizer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from about_us.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home_page'),

    path('meals/', include(('meals.urls', 'meals'), namespace='meals')),
    path('reservation/', include(('reservation.urls', 'reservation'), namespace='reservation')),
    path('contact_us/', include(('contact.urls', 'contact'), namespace='contact')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('about_us/', include(('about_us.urls', 'about_us'), namespace='about_us')),
    path('catering/', include(('catering.urls', 'catering'), namespace='catering')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('user/', include(('user.urls', 'user'), namespace='user')),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import posts_list, posts_categories, post_leave_comment, tags_list
from .views import PostDetail, TagDetail


urlpatterns = [
    path('', posts_list, name='posts_list_url'),
    path('categories', posts_categories, name='posts_categories_url'),
    path('post/<str:slug>', PostDetail.as_view(), name='post_details_url'),
    path('comment/<str:slug>', post_leave_comment, name='post_leave_comment_url'),
    path('tag_s', tags_list, name='tags_list_url'),
    path('tag/<str:slug>/', TagDetail.as_view(), name='tag_details_url'),
]

cart/urls.py
from django.urls import path

from .views import cart_details, add_to_cart, remove_from_cart, full_remove_from_cart

urlpatterns = [
    path('', cart_details, name='cart_details_url'),
    path('add/<str:slug>', add_to_cart, name='add_to_cart_url'),
    path('remove/<str:slug>', remove_from_cart, name='remove_from_cart_url'),
    path('full_remove/<str:slug>', full_remove_from_cart, name='full_remove_from_cart_url')

]

catering/urls.py
from django.urls import path
from .views import catering_products_list, catering_product_details


urlpatterns = [
    path('', catering_products_list, name='catering_products_list_url'),
    path('<str:slug>', catering_product_details, name='catering_product_details_url'),
]

order/urls.py
from django.urls import path
from .views import order_create, order_history, order_details


urlpatterns = [
    path('create_order/', order_create, name='order_create_url'),
    path('order_history/', order_history, name='order_history_url'),
    path('order_details/<int:order_id>', order_details, name='order_details_url'),

]

cart/models.py
from django.db import models
from catering.models import CateringProduct


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['date_added']

    def __str__(self):
        return f'{self.cart_id}'


class CartItem(models.Model):
    product = models.ForeignKey(CateringProduct, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return f'{self.product}'

cart/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404

from catering.models import CateringProduct
from .models import Cart, CartItem


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def cart_details(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', {
        'cart_items': cart_items,
        'total': total,
        'counter': counter
    })


def add_to_cart(request, slug):
    product = CateringProduct.objects.get(slug=slug)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
    cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_details_url')


def remove_from_cart(request, slug):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(CateringProduct, slug=slug)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details_url')


def full_remove_from_cart(request, slug):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(CateringProduct, slug=slug)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_details_url')

cart/templates/cart.html
{% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block content %}
    {% if not cart_items %}
        <div class="container">
            <div class="text-center">
                <hr>
                <h1>Your ordering cart is empty</h1>
                <hr>
                <p>Please click
                    <a href="{% url 'catering:catering_products_list_url' %}">
                        to continue ordering</a>
                </p>
            </div>
        </div>

    {% else %}

        <div class="container">
            <div class="text-center">
                <hr>
                <h1>Your ordering cart</h1>
                <hr>
            </div>
        </div>
        <div class="container">
            <div class="row mx-auto">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table">

                        <thead>
                        <tr>
                            <th colspan="5">Your items</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="{{ cart_items.product.get_absolute_url }}">
                                        <img src="{{ cart_item.product.image.url }}" alt=""
                                             style="width:4em; height:4em;">
                                    </a>
                                </td>
                                <td class="text-left">
                                    {{ cart_item.product.name }}
                                    <br>
                                    Unit price: {{ cart_item.product.price }}
                                    <br>
                                    Quantity: {{ cart_item.quantity }} x {{ cart_item.product.price }}
                                </td>
                                <td>
                                    Total: {{ cart_item.sub_total }}
                                </td>
                                {% if cart_item.quantity < cart_item.product.stock %}
                                    <td>
                                        <a href="{% url 'cart:add_to_cart_url' cart_item.product.slug %}">
                                            <i class="fa fa-plus-circle" style="color: #FF5E18"></i>
                                        </a>&nbsp;
                                        <a href="{% url 'cart:full_remove_from_cart_url' cart_item.product.slug %}">
                                            <i class="fa fa-trash" style="color: #FF5E18"></i>
                                        </a>&nbsp;
                                        <a href="{% url 'cart:remove_from_cart_url' cart_item.product.slug %}">
                                            <i class="fa fa-minus-circle" style="color: #FF5E18"></i>
                                        </a>
                                    </td>
                                {% else %}
                                    <td>
                                        <a href="{% url 'cart:full_remove_from_cart_url' cart_item.product.slug %}">
                                            <i class="fa fa-trash" style="color: #FF5E18"></i>
                                        </a>&nbsp;
                                        <a href="{% url 'cart:remove_from_cart_url' cart_item.product.slug %}">
                                            <i class="fa fa-minus-circle" style="color: #FF5E18"></i>
                                        </a>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Checkout</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Please review your ordering cart items before proceeding with the order payment</td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                There are <strong>{{ counter }} items in your cart</strong>
                                Your total is: <strong>${{ total }}</strong>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="mx-auto">
                        <a href="{% url 'catering:catering_products_list_url' %}" class="btn btn-default cart-btn">
                            Continue Ordering
                        </a>
                        <a href="{% url 'order:order_create_url' %}" class="btn btn-default cart-btn">
                            Create Order
                        </a>
                    </div>
                </div>
            </div>
            <br>
        </div>
    {% endif %}
{% endblock %}